# Generated by Django 6.0.5 on 2026-06-16 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Reja nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx (USD)')),
                ('price_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Narx (UZS)')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Muddat (kun)')),
                ('features', models.JSONField(default=list, verbose_name='Imkoniyatlar')),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('payme', 'Payme'), ('click', 'Click'), ('sandbox', 'Sandbox (Test)')], max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', '⏳ Kutilmoqda'), ('completed', '✅ Bajarildi'), ('failed', '❌ Muvaffaqiyatsiz'), ('refunded', '↩️ Qaytarildi')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
