# Generated by Django 6.0.5 on 2026-06-16 12:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('xp_reward', models.IntegerField(default=50)),
                ('condition_type', models.CharField(choices=[('quests_completed', 'Topshiriqlar soni'), ('xp_earned', 'XP miqdori'), ('streak_days', 'Ketma-ket kunlar'), ('scripts_written', 'Yozilgan skriptlar'), ('level_reached', 'Daraja')], max_length=50)),
                ('condition_value', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['condition_value'],
            },
        ),
        migrations.CreateModel(
            name='CyberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tajriba ochkolari')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Daraja')),
                ('rank', models.CharField(choices=[('recruit', '🔰 Recruit'), ('script_kiddie', '👶 Script Kiddie'), ('hacker', '💻 Hacker'), ('elite_hacker', '🔥 Elite Hacker'), ('cyber_ninja', '🥷 Cyber Ninja'), ('shadow_master', '👑 Shadow Master')], default='recruit', max_length=30, verbose_name='Rang')),
                ('quests_completed', models.IntegerField(default=0, verbose_name='Bajarilgan topshiriqlar')),
                ('scripts_written', models.IntegerField(default=0, verbose_name='Yozilgan skriptlar')),
                ('correct_scripts', models.IntegerField(default=0, verbose_name="To'g'ri skriptlar")),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='Sarflangan vaqt (daqiqa)')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Ketma-ket kunlar')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='Premium muddati')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='Bio')),
                ('github_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiber Profil',
                'verbose_name_plural': 'Kiber Profillar',
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirish tarixi',
                'verbose_name_plural': 'Kirish tarixi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi yutuqi',
                'verbose_name_plural': 'Foydalanuvchi yutuqlari',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
