# Generated by Django 6.0.5 on 2026-06-16 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('tier', models.CharField(choices=[('junior', '🟢 Junior'), ('middle', '🟡 Middle'), ('senior', '🔴 Senior')], default='junior', max_length=20)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=True, verbose_name='Bepul')),
                ('xp_reward', models.IntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Topshiriq nomi')),
                ('slug', models.SlugField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('theory_content', models.TextField(verbose_name='Nazariya (Markdown)')),
                ('task_description', models.TextField(verbose_name='Vazifa tavsifi')),
                ('hint', models.TextField(blank=True, default='', verbose_name='Maslahat')),
                ('expected_output', models.TextField(blank=True, verbose_name='Kutilgan natija')),
                ('validation_script', models.TextField(blank=True, verbose_name='Tekshirish skripti (Python)')),
                ('validation_type', models.CharField(choices=[('output_match', 'Natija mos kelishi'), ('file_exists', 'Fayl mavjudligi'), ('file_content', 'Fayl tarkibi'), ('custom_script', 'Maxsus skript')], default='output_match', max_length=30)),
                ('setup_script', models.TextField(blank=True, verbose_name="Boshlang'ich muhit skripti")),
                ('starter_code', models.TextField(blank=True, verbose_name="Boshlang'ich kod")),
                ('difficulty', models.CharField(choices=[('easy', '🟢 Oson'), ('medium', "🟡 O'rtacha"), ('hard', '🔴 Qiyin'), ('elite', '💀 Elite')], default='easy', max_length=20)),
                ('xp_reward', models.IntegerField(default=25)),
                ('time_limit', models.IntegerField(default=30, verbose_name='Vaqt limiti (soniya)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='courses.course')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('last_code', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topshiriq progressi',
                'verbose_name_plural': 'Topshiriq progresslari',
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
