# Generated by Django 6.0.5 on 2026-06-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='xp_reward',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='setup_script',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='starter_code',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='theory_content',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='questprogress',
            name='last_code',
        ),
        migrations.AddField(
            model_name='quest',
            name='command_trigger',
            field=models.CharField(default='whoami', max_length=255, verbose_name="Kutilayotgan terminal buyrug'i"),
        ),
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.TextField(default="Topshiriq sharti tez orada qo'shiladi.", verbose_name='Topshiriq sharti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='hint_code',
            field=models.TextField(blank=True, null=True, verbose_name='Maslahat / Misol Kodlar'),
        ),
        migrations.AddField(
            model_name='quest',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Darslik Linki'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(default='🛡️', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='validation_type',
            field=models.CharField(choices=[('command_match', "Terminal buyrug'i mosligi"), ('output_match', 'Natija mos kelishi'), ('file_exists', 'Fayl mavjudligi'), ('file_content', 'Fayl tarkibi'), ('custom_script', 'Maxsus skript')], default='command_match', max_length=30),
        ),
        migrations.AlterField(
            model_name='quest',
            name='xp_reward',
            field=models.IntegerField(default=100, verbose_name='Beriladigan EXP ochkosi'),
        ),
    ]
