# Generated by Django 6.0.5 on 2026-06-16 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(verbose_name='Yozilgan kod')),
                ('output', models.TextField(blank=True, default='', verbose_name='Natija')),
                ('error_output', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', '✅ Muvaffaqiyatli'), ('failed', '❌ Muvaffaqiyatsiz'), ('error', '⚠️ Xatolik'), ('timeout', '⏰ Vaqt tugadi')], default='failed', max_length=20)),
                ('execution_time', models.FloatField(default=0, verbose_name='Bajarilish vaqti (soniya)')),
                ('is_correct', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bajarilish tarixi',
                'verbose_name_plural': 'Bajarilish tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
